# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credocommon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
