# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("credocommon", "0002_auto_20180515_1754")]

    operations = [
        migrations.AddField(
            model_name="ping",
            name="on_time",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="ping",
            name="time_received",
            field=models.BigIntegerField(blank=True, default=1527676072000),
            preserve_default=False,
        ),
    ]
