# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credocommon', '0003_auto_20180530_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='brightness',
            field=models.FloatField(null=True),
        ),
    ]
