# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("credocommon", "0004_detection_brightness")]

    operations = [
        migrations.RemoveField(model_name="detection", name="brightness"),
        migrations.RemoveField(model_name="detection", name="d_id"),
        migrations.AddField(
            model_name="detection", name="x", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="detection", name="y", field=models.IntegerField(null=True)
        ),
        migrations.AlterField(
            model_name="detection", name="height", field=models.IntegerField(null=True)
        ),
        migrations.AlterField(
            model_name="detection", name="width", field=models.IntegerField(null=True)
        ),
    ]
