from __future__ import unicode_literals

"""
Django settings for credo project.

Generated by 'django-admin startproject' using Django 1.11.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY", "s&8vuuw2%e2ael_rx8a9(ucl5$mx(r80+j+!m!j@y6m2+*s4zb"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

INTERNAL_IPS = ("127.0.0.1",)


# Application definition

INSTALLED_APPS = [
    "credoapiv2.apps.Credoapiv2Config",
    "credocommon.apps.CredocommonConfig",
    "credoweb.apps.CredowebConfig",
    "acra.apps.AcraConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.humanize",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "debug_toolbar",
    "rest_framework",
    "django_rq",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = "credo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

LOGIN_URL = "/web/login/"
LOGIN_REDIRECT_URL = "/web/"

WSGI_APPLICATION = "credo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/",
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        "KEY_PREFIX": "credo-webapp",
        "VERSION": 2,
    }
}

RQ = {"DEFAULT_RESULT_TTL": 3600 * 24 * 7}

RQ_QUEUES = {
    "default": {"HOST": "localhost", "PORT": 6379, "DB": 1, "DEFAULT_TIMEOUT": 3600},
    "data_export": {
        "HOST": "localhost",
        "PORT": 6379,
        "DB": 1,
        "DEFAULT_TIMEOUT": 3600 * 24,
    },
    "low": {"HOST": "localhost", "PORT": 6379, "DB": 1, "DEFAULT_TIMEOUT": 3600},
    "migration": {"HOST": "localhost", "PORT": 6379, "DB": 1, "DEFAULT_TIMEOUT": 3600},
}

RQ_SHOW_ADMIN_LINK = True

EXPORT_TMP_FOLDER = "credo_export/"

S3_BUCKET = "credo"
S3_EXPIRES_IN = 3600 * 24 * 7  # 7 days
S3_ACCESS_KEY_ID = ""
S3_SECRET_KEY = ""
S3_ENDPOINT_URL = ""

AUTH_USER_MODEL = "credocommon.User"

AUTHENTICATION_BACKENDS = (
    "credoapiv2.backends.TokenBackend",
    "credocommon.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
)

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

OAUTH_PROVIDERS = {}
# {
#    "scistarter": {
#        "discovery_endpoint": "https://scistarter.org/.well-known/openid-configuration",
#        "token_endpoint": "https://scistarter.org/token",
#        "userinfo_endpoint": "https://scistarter.org/userinfo",
#        "redirect_uri": "science.credo.mobiledetector.scheme:/oauth2redirect",
#        "client_id": "",
#        "client_secret": "",
#    }
# }


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Warsaw"

USE_I18N = True

USE_L10N = True

USE_TZ = True


STATIC_URL = "/static/"
STATIC_ROOT = os.path.join("/app/static/")

EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "localhost")

REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_CLASSES": ("rest_framework.throttling.ScopedRateThrottle",),
    "DEFAULT_THROTTLE_RATES": {"data_export": "400/day", "mapping_export": "30/day"},
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"level": "INFO", "class": "logging.StreamHandler"}},
    "loggers": {
        "credoapiv2": {"handlers": ["console"], "level": "INFO"},
        "credocommon": {"handlers": ["console"], "level": "INFO"},
        "credoweb": {"handlers": ["console"], "level": "INFO"},
    },
}


LOCAL_APPS = []
LOCAL_MIDDLEWARE_PRE = []
LOCAL_MIDDLEWARE_POST = []

try:
    from local_settings import *

    INSTALLED_APPS += LOCAL_APPS
    MIDDLEWARE = LOCAL_MIDDLEWARE_PRE + MIDDLEWARE + LOCAL_MIDDLEWARE_POST
except ImportError:
    pass
